/*
 * zx81.hpp - ZX81 machine emulation
 *
 * The ZX81 is fundamentally different from the ZX Spectrum:
 * - Z80A CPU at 3.25 MHz (not 3.5 MHz)
 * - 8KB ROM + 1KB-16KB RAM
 * - Monochrome character-based display (32x24 characters)
 * - Display generated by CPU via NMI-driven routine
 * - No ULA bitmap display, no colour attributes
 * - NMI generator controlled by I/O port writes
 *
 * Written by
 *  Mike Daley <michael_daley@icloud.com>
 */

#pragma once

#include "../zx_spectrum.hpp"
#include <array>
#include <cstdint>

namespace zxspec::zx81 {

class ZX81 : public ZXSpectrum {
public:
    ZX81();
    ~ZX81() override;

    // Machine interface
    void init() override;
    void reset() override;

    // ZX81 has its own frame execution with NMI generation
    void runFrame() override;
    void renderDisplay() override;

    // ZX81 uses its own framebuffer (not the Spectrum Display class)
    const uint8_t* getFramebuffer() const override;
    int getFramebufferSize() const override;
    const uint8_t* getSignalBuffer() const override;
    int getSignalBufferSize() const override;

    // Snapshot loaders (ZX81 formats - stubs for now)
    void loadSNA(const uint8_t* data, uint32_t size) override;
    void loadZ80(const uint8_t* data, uint32_t size) override;
    void loadTZX(const uint8_t* data, uint32_t size) override;
    void loadTAP(const uint8_t* data, uint32_t size) override;
    void loadTZXTape(const uint8_t* data, uint32_t size) override;

    // .P file loader (ZX81 native format)
    void loadP(const uint8_t* data, uint32_t size);

    // Core virtual overrides
    uint8_t coreMemoryRead(uint16_t address) override;
    void coreMemoryWrite(uint16_t address, uint8_t data) override;
    void coreMemoryContention(uint16_t address, uint32_t tstates) override;
    void coreNoMreqContention(uint16_t address, uint32_t tstates) override;
    uint8_t coreIORead(uint16_t address) override;
    void coreIOWrite(uint16_t address, uint8_t data) override;
    uint8_t coreDebugRead(uint16_t address) const override;
    void coreDebugWrite(uint16_t address, uint8_t data) override;

    // No Spectranet or Opus on ZX81
    void reloadSpectranetROM() override {}
    void reloadOpusROM() override {}
    void reloadCurrahSpeechROM() override {}

    // Screen memory (returns start of RAM for compatibility)
    uint8_t* getScreenMemory() override;
    const uint8_t* getScreenMemory() const override;

    // ZX81 has no BASIC breakpoint support (different ROM addresses)
    uint16_t getStmtLoopAddr() const override { return 0xFFFF; }
    uint16_t getMainReportAddr() const override { return 0xFFFF; }

private:
    // Render the ZX81 character display from D-FILE into the framebuffer
    void renderZX81Display();

    // Read a byte from the ZX81 address space (for display rendering)
    uint8_t readAddress(uint16_t address) const;

    // NMI generator state
    bool nmiGeneratorOn_ = false;
    uint32_t nmiTsAccumulator_ = 0;

    // HSYNC/VSYNC state
    bool vsyncActive_ = false;

    // INT edge detection: track previous R register bit 6 state
    // INT fires on the transition of bit 6 from 1 → 0, not as a level
    uint8_t prevRBit6_ = 0x40;

    // ZX81's own framebuffer (RGBA, same dimensions as Spectrum)
    std::array<uint8_t, FRAMEBUFFER_SIZE> zx81Framebuffer_{};
    std::array<uint8_t, SIGNAL_BUFFER_SIZE> zx81SignalBuffer_{};

    // ZX81 CPU clock frequency
    static constexpr double ZX81_CPU_CLOCK_HZ = 3250000.0;

    // T-states per scanline
    static constexpr uint32_t ZX81_TS_PER_LINE = 207;
};

} // namespace zxspec::zx81
