#!/bin/bash

# Generate C++ source file containing ROM data as byte arrays
# Usage: generate_roms.sh <rom_directory> <output_file>

ROM_DIR="$1"
OUTPUT_FILE="$2"

if [ -z "$ROM_DIR" ] || [ -z "$OUTPUT_FILE" ]; then
    echo "Usage: $0 <rom_directory> <output_file>"
    exit 1
fi

# Start the output file
cat > "$OUTPUT_FILE" << 'EOF'
// Auto-generated ROM data - DO NOT EDIT
// Generated by generate_roms.sh

#include <cstdint>
#include <cstddef>

namespace roms {

EOF

# Function to convert a binary file to a C array
generate_array() {
    local file="$1"
    local name="$2"

    if [ ! -f "$file" ]; then
        echo "// ROM file not found: $file" >> "$OUTPUT_FILE"
        echo "const uint8_t ${name}[] = {};" >> "$OUTPUT_FILE"
        echo "const size_t ${name}_SIZE = 0;" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        return
    fi

    local size=$(wc -c < "$file" | tr -d ' ')

    echo "// $(basename "$file")" >> "$OUTPUT_FILE"
    echo "const uint8_t ${name}[] = {" >> "$OUTPUT_FILE"

    xxd -i < "$file" | sed 's/^/    /' >> "$OUTPUT_FILE"

    echo "};" >> "$OUTPUT_FILE"
    echo "const size_t ${name}_SIZE = $size;" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
}

# Generate arrays for all ROMs
generate_array "$ROM_DIR/48.rom" "ROM_48K"
generate_array "$ROM_DIR/128-0.rom" "ROM_128K_0"
generate_array "$ROM_DIR/128-1.rom" "ROM_128K_1"

# Close namespace
echo "} // namespace roms" >> "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
